### ISSUE TITLE
(Open chords) Fret is not showed and cannot sound in IPad and IPhone

### ISSUE THREAD

**Issue by dengqinghua** [andygock/chordy-svg#1]
Andy:

Thk for your chordy-svg, I have used it in my blog: [here](http://blog.dengqinghua.net/%E3%81%82%E3%81%AE%E6%97%A5%E3%81%AE%E5%B8%B0%E3%82%8A%E9%81%93.html)

But I have two problems:

1. This [Dadd9](http://blog.dengqinghua.net/%E3%81%82%E3%81%AE%E6%97%A5%E3%81%AE%E5%B8%B0%E3%82%8A%E9%81%93.html#dadd9) chord, I have set

```
     shape: xx0770,
     root: 3
```

   But it did not show the fret7,  Instead of this:

   **Images Example Begin**
<img width="770" alt="image" src="https://user-images.githubusercontent.com/8321870/38652359-2a04e33a-3df5-11e8-8c51-1cceed8d4c64.png">
   **Images Example End**

I have tested in my MacOS Chrome(65.0) and Firefox(50.0.0.1)

2. I used the source file in your demo: https://chords.gock.net

  but the sound: 
    
   **Images Example Begin**
<img width="770" alt="image" src="https://user-images.githubusercontent.com/8321870/38652359-2a04e33a-3df5-11e8-8c51-1cceed8d4c64.png">
   **Images Example End**

   here cannot be heard in My IPhone6(11.2) and iPad Mini4(11.2.6(15D100))

   Thks again and forgive me my poor English grammar.

**Comment by andygock** [comment]
Hi @dengqinghua 

Thanks for the feedback. I've actually never tested it properly or intended to use it with open chords, or with inversions.

I'll look into it in the future though, because it would be good if it did work with those types of chords too.

Andy

**Comment by dengqinghua** [comment]
@andygock 
   Thank you for your reply.

   There is another fret chord note problem. But I have found a solution. Code is [here](https://github.com/dengqinghua/roses/blob/master/assets/javascripts/chord.js#L63)

   ```javascript
    var svg = new ChordySvg(
      {
      shape: $(this).attr("data-shape"),
      root: $(this).attr("data-root"),
      name: $(this).attr("data-name")
    },
    { target: this });

    var notesArray = [];

    svg.notes().forEach(function(note, index) {
      // 解决空弦对不上的问题
      if (note == '40') {
        notesArray[index] = 'E2';
      } else if (note == '45') {
        notesArray[index] = 'A2';
      } else if (note == '50') {
        notesArray[index] = 'D3';
      } else if (note == '55') {
        notesArray[index] = 'G3';
      } else if (note == '59') {
        notesArray[index] = 'B3';
      } else if (note == '64') {
        notesArray[index] = 'E4';
      } else {
        notesArray[index] = note;
      }
   })
   ```
  
   You can see that the note is not right when the string is opened, which will make the sound weird if I continue to use Tone js.

   Very thks.

Dengqinghua

**Comment by andygock** [comment]
Hi @dengqinghua 

Can you check with my latest commit 497eb52db975445aaf6a25221a0ce084051ecf02

I've tested it and it should now:

* display fret number for open chords where root is a open string
* audio preview should work for open chords the same as it does for movable chords

There are newly built files in `dist/`

You shouldn't need to perform the hack you posted above any more.

There's still a lot more to do regarding open chords though, like displaying intervals and showing the root etc.

**Comment by andygock** [comment]
I'm closing this. Reopen it if you have further problems.

The iPad and iPhone issue isn't part of this library, it relates to the implementation of Tone.js and not part of this. This library is just for the creation of the SVG diagrams.

**Comment by dengqinghua** [comment]
I've reimported and checked. It is already worked.

Thks very much!
