### ISSUE TITLE
Are you working on this anymore?

### ISSUE THREAD

**Issue by Kernix13** [andygock/chordy-svg#14]
I think I commented before about chord names. Do you need any help with anything? I have only contributed to freeCodeCamp and it would help me if I could contribute to another repo. Do you have any issues you are working on? Let me know if you do, no big deal if you are done with this project.

**Comment by andygock** [comment]
I'm not really working on this any more unfortunately. So there is probably not much that needs contributing into. Thanks for considering to do so. Good luck finding some good projects to work on!
