### ISSUE TITLE
Some extensions are missing

### ISSUE THREAD

**Issue by torqueville** [andygock/chordy-svg#2]
Hi! Found two false positives. 

1-8x89aa is listed as C13#11, but is a plain C13. No sharp eleven.
1-8x89a8 is listed as C13b9 but no flat nine.

**Comment by andygock** [comment]
Hi @torqueville 

Thanks for your keen eye on my project!

I've fixed those chord shapes on the [chords.gock.net](https://chords.gock.net/) page now.

Regards,
Andy
