### ISSUE TITLE
installation fails

### ISSUE THREAD

**Issue by tscole** [andygock/chordy-svg#4]
Running npm install chordy-svg --save

Results in the following error:

npm ERR! code ETARGET
npm ERR! notarget No matching version found for tonal-interval@^1.1.4
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget 
npm ERR! notarget It was specified as a dependency of 'tonal'
npm ERR! notarget

**Comment by andygock** [comment]
Fixed in acce2965664cc0ec58673d4dd320df1fd49358cd with npm release `1.1.0`
